language: go

go:
  - 1.8
  - 1.11
  - tip

sudo: required

services:
  - mysql

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS rest_api_example;'

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/gorilla/mux
  - go get github.com/go-sql-driver/mysql

script:
  - go test -covermode=count -coverprofile=coverage.out
